In [2]:
import pandas as pd
import datetime
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
energy_df = pd.read_csv('Combined_Data_for_model_final_2.csv')

In [5]:
energy_df.head()

,Unnamed: 0,Date,Haryana Load (MW),temp,dew,humidity,windspeed,winddir,cloudcover,visibility
0,0,2016-01-01 00:15:00,4099.37,11.0,7.0,76.36,0.0,0.0,27.4,1.0
1,1,2016-01-01 00:30:00,3995.64,11.0,7.0,76.36,0.0,0.0,27.4,1.0
2,2,2016-01-01 00:45:00,3954.80,11.0,7.0,76.36,0.0,0.0,27.4,1.0
3,3,2016-01-01 01:00:00,3904.93,11.0,8.0,81.75,0.0,0.0,27.4,1.0
4,4,2016-01-01 01:15:00,3654.68,11.0,8.0,81.75,0.0,0.0,27.4,1.0

In [7]:
year_list = []
month_list = []
for time in energy_df['Date']:
    year = str(time)[:4]
    month = str(time)[5:7]
    year_list.append(year)
    month_list.append(month)

In [8]:
months_unique = set(month_list)
months_unique

{'01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'}

In [10]:
energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210431 entries, 0 to 210430
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         210431 non-null  int64
 1   Date               210431 non-null  object
 2   Haryana Load (MW)  210431 non-null  float64
 3   temp               210431 non-null  float64
 4   dew                210431 non-null  float64
 5   humidity           210431 non-null  float64
 6   windspeed          210431 non-null  float64
 7   winddir            210431 non-null  float64
 8   cloudcover         210431 non-null  float64
 9   visibility         210431 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 16.1+ MB

In [11]:
def get_season(TimeSeries):
    
    season_list = []
    
    year_list = []
    month_list = []
    for time in TimeSeries:
        year = str(time)[:4]
        month = str(time)[5:7]
        year_list.append(year)
        month_list.append(month) 
       
    for m in month_list:
        if m=='01' or m=='02' or m=='12':
            season_list.append(0)   # Winter
        elif m=='03' or m=='04' or m=='05' or m=='06':
            season_list.append(1) #Spring-Summer
        elif m=='07' or m=='08' or m=='09':
            season_list.append(2) #Monsoon
        elif m=='10' or m=='11':
            season_list.append(3) #Autumn
            
    #season = pd.Series(season_list)
    return season_list

In [13]:
season = get_season(energy_df['Date'])

In [14]:
energy_df['Season'] = season

In [15]:
hour_list = []
for time in energy_df['Date']:
    hour = str(time)[11:13]
    hour_list.append(hour)
hour_list

['00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 '10',
 '10',
 '10',
 '11',
 '11',
 '11',
 '11',
 '12',
 '12',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '15',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '22',
 '22',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '00',
 '00',
 '00',
 '00',
 '01',
 '01',
 '01',
 '01',
 '02',
 '02',
 '02',
 '02',
 '03',
 '03',
 '03',
 '03',
 '04',
 '04',
 '04',
 '04',
 '05',
 '05',
 '05',
 '05',
 '06',
 '06',
 '06',
 '06',
 '07',
 '07',
 '07',
 '07',
 '08',
 '08',
 '08',
 '08',
 '09',
 '09',
 '09',
 '09',
 '10',
 ...]

In [17]:
energy_df['Hour of day'] = [int(hour) for hour in hour_list]

In [20]:
energy_df

,Unnamed: 0,Date,Haryana Load (MW),temp,dew,humidity,windspeed,winddir,cloudcover,visibility,Season,Hour of day
0,0,2016-01-01 00:15:00,4099.37,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0
1,1,2016-01-01 00:30:00,3995.64,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0
2,2,2016-01-01 00:45:00,3954.80,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0
3,3,2016-01-01 01:00:00,3904.93,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1
4,4,2016-01-01 01:15:00,3654.68,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
210426,210426,2021-12-31 22:45:00,4712.55,10.0,8.0,87.38,0.0,0.0,27.4,2.0,0,22
210427,210427,2021-12-31 23:00:00,4649.58,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23
210428,210428,2021-12-31 23:15:00,4571.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23
210429,210429,2021-12-31 23:30:00,4510.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23
210430,210430,2021-12-31 23:45:00,4449.94,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23

In [21]:
day_list = []
energy_df['Date'] = pd.to_datetime(energy_df['Date'])
for time in energy_df['Date']:
    day = time.weekday()
    day_list.append(day)
energy_df['Day of Week'] = day_list

In [22]:
energy_df

,Unnamed: 0,Date,Haryana Load (MW),temp,dew,humidity,windspeed,winddir,cloudcover,visibility,Season,Hour of day,Day of Week
0,0,2016-01-01 00:15:00,4099.37,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4
1,1,2016-01-01 00:30:00,3995.64,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4
2,2,2016-01-01 00:45:00,3954.80,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4
3,3,2016-01-01 01:00:00,3904.93,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1,4
4,4,2016-01-01 01:15:00,3654.68,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210426,210426,2021-12-31 22:45:00,4712.55,10.0,8.0,87.38,0.0,0.0,27.4,2.0,0,22,4
210427,210427,2021-12-31 23:00:00,4649.58,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4
210428,210428,2021-12-31 23:15:00,4571.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4
210429,210429,2021-12-31 23:30:00,4510.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4
210430,210430,2021-12-31 23:45:00,4449.94,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4

In [23]:
energy_df['Is Weekend'] = [day == 5 or day == 6 for day in energy_df['Day of Week']]

In [24]:
energy_df

,Unnamed: 0,Date,Haryana Load (MW),temp,dew,humidity,windspeed,winddir,cloudcover,visibility,Season,Hour of day,Day of Week,Is Weekend
0,0,2016-01-01 00:15:00,4099.37,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4,False
1,1,2016-01-01 00:30:00,3995.64,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4,False
2,2,2016-01-01 00:45:00,3954.80,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4,False
3,3,2016-01-01 01:00:00,3904.93,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1,4,False
4,4,2016-01-01 01:15:00,3654.68,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210426,210426,2021-12-31 22:45:00,4712.55,10.0,8.0,87.38,0.0,0.0,27.4,2.0,0,22,4,False
210427,210427,2021-12-31 23:00:00,4649.58,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False
210428,210428,2021-12-31 23:15:00,4571.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False
210429,210429,2021-12-31 23:30:00,4510.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False
210430,210430,2021-12-31 23:45:00,4449.94,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False

In [25]:
clean_weekend = []
for b in energy_df['Is Weekend']:
    if b==True:
        clean_weekend.append(1)
    elif b==False:
        clean_weekend.append(0)
energy_df['Is Weekend Clean'] = clean_weekend

In [26]:
energy_df

,Unnamed: 0,Date,Haryana Load (MW),temp,dew,humidity,windspeed,winddir,cloudcover,visibility,Season,Hour of day,Day of Week,Is Weekend,Is Weekend Clean
0,0,2016-01-01 00:15:00,4099.37,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4,False,0
1,1,2016-01-01 00:30:00,3995.64,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4,False,0
2,2,2016-01-01 00:45:00,3954.80,11.0,7.0,76.36,0.0,0.0,27.4,1.0,0,0,4,False,0
3,3,2016-01-01 01:00:00,3904.93,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1,4,False,0
4,4,2016-01-01 01:15:00,3654.68,11.0,8.0,81.75,0.0,0.0,27.4,1.0,0,1,4,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210426,210426,2021-12-31 22:45:00,4712.55,10.0,8.0,87.38,0.0,0.0,27.4,2.0,0,22,4,False,0
210427,210427,2021-12-31 23:00:00,4649.58,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False,0
210428,210428,2021-12-31 23:15:00,4571.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False,0
210429,210429,2021-12-31 23:30:00,4510.39,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False,0
210430,210430,2021-12-31 23:45:00,4449.94,9.2,7.3,88.04,0.0,0.0,28.5,1.3,0,23,4,False,0

In [27]:
energy_df = energy_df.drop(columns=['Is Weekend'])

In [28]:
energy_df.corr()

,Unnamed: 0,Haryana Load (MW),temp,dew,humidity,windspeed,winddir,cloudcover,visibility,Season,Hour of day,Day of Week,Is Weekend Clean
Unnamed: 0,1.000000,0.150388,-0.040199,0.061319,0.111563,-0.043855,-0.057483,0.068373,0.021891,0.096422,0.000442,-0.001181,-0.002004
Haryana Load (MW),0.150388,1.000000,0.504668,0.617157,0.016372,0.087153,-0.029084,0.287901,0.325990,0.259011,0.114884,-0.041774,-0.056105
temp,-0.040199,0.504668,1.000000,0.538345,-0.588910,0.362062,0.134242,0.239265,0.692226,0.363203,0.219212,-0.005567,-0.007670
dew,0.061319,0.617157,0.538345,1.000000,0.327262,0.073790,-0.165958,0.554322,0.303009,0.462137,-0.013864,0.005373,-0.000827
humidity,0.111563,0.016372,-0.588910,0.327262,1.000000,-0.327792,-0.303280,0.284030,-0.499458,0.006129,-0.280852,0.010816,0.007714
windspeed,-0.043855,0.087153,0.362062,0.073790,-0.327792,1.000000,0.483971,0.179585,0.345374,-0.082914,0.141720,0.014333,0.012012
winddir,-0.057483,-0.029084,0.134242,-0.165958,-0.303280,0.483971,1.000000,-0.084202,0.134194,-0.100639,0.134540,-0.006979,0.002149
cloudcover,0.068373,0.287901,0.239265,0.554322,0.284030,0.179585,-0.084202,1.000000,0.117772,0.096489,0.018671,-0.005450,-0.012627
visibility,0.021891,0.325990,0.692226,0.303009,-0.499458,0.345374,0.134194,0.117772,1.000000,0.225875,0.191557,-0.005567,0.003059
Season,0.096422,0.259011,0.363203,0.462137,0.006129,-0.082914,-0.100639,0.096489,0.225875,1.000000,-0.000010,-0.003186,-0.001878
Hour of day,0.000442,0.114884,0.219212,-0.013864,-0.280852,0.141720,0.134540,0.018671,0.191557,-0.000010,1.000000,0.000004,-0.000005
Day of Week,-0.001181,-0.041774,-0.005567,0.005373,0.010816,0.014333,-0.006979,-0.005450,-0.005567,-0.003186,0.000004,1.000000,0.790311
Is Weekend Clean,-0.002004,-0.056105,-0.007670,-0.000827,0.007714,0.012012,0.002149,-0.012627,0.003059,-0.001878,-0.000005,0.790311,1.000000

In [29]:
energy_df = energy_df[['Date', 'Haryana Load (MW)', 'temp', 'dew', 'cloudcover', 'visibility', 'Season', 'Hour of day', 'Day of Week', 'Is Weekend Clean']]

In [30]:
energy_df

,Date,Haryana Load (MW),temp,dew,cloudcover,visibility,Season,Hour of day,Day of Week,Is Weekend Clean
0,2016-01-01 00:15:00,4099.37,11.0,7.0,27.4,1.0,0,0,4,0
1,2016-01-01 00:30:00,3995.64,11.0,7.0,27.4,1.0,0,0,4,0
2,2016-01-01 00:45:00,3954.80,11.0,7.0,27.4,1.0,0,0,4,0
3,2016-01-01 01:00:00,3904.93,11.0,8.0,27.4,1.0,0,1,4,0
4,2016-01-01 01:15:00,3654.68,11.0,8.0,27.4,1.0,0,1,4,0
...,...,...,...,...,...,...,...,...,...,...
210426,2021-12-31 22:45:00,4712.55,10.0,8.0,27.4,2.0,0,22,4,0
210427,2021-12-31 23:00:00,4649.58,9.2,7.3,28.5,1.3,0,23,4,0
210428,2021-12-31 23:15:00,4571.39,9.2,7.3,28.5,1.3,0,23,4,0
210429,2021-12-31 23:30:00,4510.39,9.2,7.3,28.5,1.3,0,23,4,0
210430,2021-12-31 23:45:00,4449.94,9.2,7.3,28.5,1.3,0,23,4,0

In [31]:
energy_df.to_csv('Complete_Dataset_added_Calendar_features.csv')