In [1]:
import pandas as pd

In [5]:
countries_holidays = pd.read_csv('holiday_dates.csv')

In [6]:
countries_holidays

,Unnamed: 0,country_code,country_name,country_holiday_dates,country_holiday
0,0,US,United States,1950-01-01,New Year's Day
1,1,US,United States,1950-01-02,'New Year's Day' observed
2,2,US,United States,1950-02-22,Presidents' Day
3,3,US,United States,1950-07-04,Independence Day
4,4,US,United States,1950-09-04,Labor Day
...,...,...,...,...,...
178783,178783,GP,Guadeloupe,2049-07-14,Bastille Day
178784,178784,GP,Guadeloupe,2049-08-15,Assumption of Mary
178785,178785,GP,Guadeloupe,2049-11-01,All Saints' Day
178786,178786,GP,Guadeloupe,2049-11-11,Armistice Day
178787,178787,GP,Guadeloupe,2049-12-25,Christmas Day

In [8]:
india_holidays = countries_holidays[countries_holidays['country_name'] == 'India']

In [9]:
india_holidays

,Unnamed: 0,country_code,country_name,country_holiday_dates,country_holiday
32082,32082,IN,India,2005-01-26,Republic Day
32083,32083,IN,India,2005-03-08,Maha Shivaratri/Shivaratri
32084,32084,IN,India,2005-03-25,Good Friday
32085,32085,IN,India,2005-04-17,Rama Navami
32086,32086,IN,India,2005-04-22,Mahavir Jayanti
...,...,...,...,...,...
32351,32351,IN,India,2021-10-02,Mahatma Gandhi Jayanti
32352,32352,IN,India,2021-10-15,Dussehra
32353,32353,IN,India,2021-11-04,Diwali/Deepavali
32354,32354,IN,India,2021-11-19,Guru Nanak Jayanti
32355,32355,IN,India,2021-12-25,Christmas

In [12]:
india_holidays = india_holidays[['country_holiday_dates', 'country_holiday']]

In [15]:
india_holidays.reset_index(inplace=True)

In [18]:
india_holidays.drop(columns = 'index', inplace=True)

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [19]:
india_holidays

    country_holiday_dates             country_holiday
0              2005-01-26                Republic Day
1              2005-03-08  Maha Shivaratri/Shivaratri
2              2005-03-25                 Good Friday
3              2005-04-17                 Rama Navami
4              2005-04-22             Mahavir Jayanti
..                    ...                         ...
269            2021-10-02      Mahatma Gandhi Jayanti
270            2021-10-15                    Dussehra
271            2021-11-04            Diwali/Deepavali
272            2021-11-19          Guru Nanak Jayanti
273            2021-12-25                   Christmas

[274 rows x 2 columns]

In [26]:
india_holidays[india_holidays['country_holiday_dates'] == '2016-01-26']

    country_holiday_dates country_holiday
168            2016-01-26    Republic Day

In [28]:
india_holidays = india_holidays[168:]

In [31]:
india_holidays.reset_index(inplace=True)

In [34]:
india_holidays.drop(columns='index', inplace=True)

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [35]:
india_holidays

    country_holiday_dates             country_holiday
0              2016-01-26                Republic Day
1              2016-03-07  Maha Shivaratri/Shivaratri
2              2016-03-25                 Good Friday
3              2016-04-15                 Rama Navami
4              2016-04-20             Mahavir Jayanti
..                    ...                         ...
101            2021-10-02      Mahatma Gandhi Jayanti
102            2021-10-15                    Dussehra
103            2021-11-04            Diwali/Deepavali
104            2021-11-19          Guru Nanak Jayanti
105            2021-12-25                   Christmas

[106 rows x 2 columns]

In [36]:
india_holidays.to_csv('India_Holidays.csv')